/* eslint-disable import/extensions */
export const LOAD_GAME = 'LOAD_GAME'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SAVE_INFO_ORDERS = 'SAVE_INFO_ORDERS'
export const MOBILE_MODE = 'MOBILE_MODE'
export const FILTER_SEARCH = 'FILTER_SEARCH'
export const FILTER_VARIOUS = 'FILTER_VARIOUS'
export const FILTER_PATFORM = 'FILTER_PATFORM'
export const FILTER_TYPE = 'FILTER_TYPE'
export const SEND_ORDER = 'SEND_ORDER'
